### ISSUE TITLE
추가 기능 지원이 가능한지 문의드립니다.

### ISSUE THREAD

**Issue by hwangbok** [nhnent/tui.tree#32]
안녕하세요!
NHN고도 정황복 agni@godo.co.kr라고 합니다.

저희가 해당 콤포넌트를 적용하려고 하는데요
현재 버전 중에는 일부 없는 기능이 있어 추가적으로 개발 및 제공이 가능한지 여쭤봅니다.

1) 트리 전체영역 하단 사이즈 조정 (높이조절)
2) 카테고리 선택된 상태에서 엔터 입력시 수정 가능한 상태
3) 15자 이상 입력된 카테고리명은 줄바꿈 되어 노출
4) 트리 전체영역 우측 사이즈 조정  (가로조절)
=> 사이즈 늘어났을때 카테고리명 한줄로 표기
5) 카테고리 마우스 우클릭시 복사기능
6) 스크롤 - 등록된 카테고리가 특정 갯수가 넘으면 스크롤 처리
7) 카테고리 이름변경시 x 버튼 추가 (input 박스 내용지우기)
8) 등록된 카테고리 선택시 + 노출되어 하위 카테고리 생성

추가적으로 개발이 가능한 부분인지 답변 또는 메일로 회신 부탁드립니다. 
감사합니다. 수고하세요~

**Comment by seonim-ryu** [comment]
@hwangbok 
안녕하세요 :) 위에 내용들은 확인해서 메일로 다시 전달드리겠습니다.

**Comment by kyuwoo-choi** [comment]
두레이 https://nhnent.dooray.com/project/posts/2186753088481674681 에서 관리.
이슈 닫습니다.
